<?php
/**
 * @file
 *   Views Matrix module file.
 */
use Drupal\Component\Utility\Html;
use Drupal\Core\Template\Attribute;

/**
 * Preprocess function for views-view-matrix.html.twig
 */
function views_matrix_preprocess_views_view_matrix(&$variables) {
  $variables['header'] = [];


//  kint($variables['view']->storage->id());
  $view = $variables['view'];
  $items = $variables['rows'];
  $variables['rows'] = '';
  $style = $view->style_plugin;
  $options = $style->options;
  $fields = $view->field;
  $xfield_id = $options['xconfig']['field'];
  $yfield_id = $options['yconfig']['field'];
  $xfield = &$fields[$xfield_id];
  $yfield = &$fields[$yfield_id];
  $columns = [];
  $rows = [];
  $columns_renders = [];
  $rows_renders = [];
  $row_header = [];
  $coordinates = [];
  $value_index_lookup = [];
  $first_column_header = $options['xconfig']['first_column'];

  // Add rows default and custom CSS classes.
  $variables['default_row_class'] = !empty($options['default_row_class']);

  foreach ($items as $id => $item) {
    $xvalue = $variables['view']->style_plugin->getField($id, $xfield_id);
    $yvalue = $variables['view']->style_plugin->getField($id, $yfield_id);

    if (!in_array($xvalue, $columns)) {
      $columns[$id] = $xvalue;
      $value_index_lookup['x'][serialize($xvalue)] = $id;
      $columns_renders[$id] = $xvalue;
    }
    // Whether we've placed this item in the header or not, we can get its
    // coordinate.
    $coordinates[$id]['x'] = $value_index_lookup['x'][serialize($xvalue)];

    if (!in_array($yvalue, $rows)) {
      $row_header[$id] = array(
        '#markup' => $yvalue,
      );
      $rows[$id] = $yvalue;
      $value_index_lookup['y'][serialize($yvalue)] = $id;
      $rows_renders[$id] = $yvalue;
    }
    $coordinates[$id]['y'] = $value_index_lookup['y'][serialize($yvalue)];

    if ($first_column_header) {
      $variables['header'][] = array(
        '#markup' => $first_column_header,
      );
    }

  }

  $column_indices = $columns_renders;
  $variables['header'][] = ' ';
  foreach (array_keys($rows_renders) as $yindex) {
    $variables['rows'][$yindex]['header'] = $row_header[$yindex];
//    array_unshift($variables['rows'][$yindex], ['header' => $row_header[$yindex]]);

    foreach (array_keys($column_indices) as $xindex) {
      $variables['rows'][$yindex][$xindex] = array(
        '#markup' => ' ',
      );
    }
  }

  foreach ($columns_renders as $xindex => $col_render) {
    $variables['header'][] = array(
      '#markup' => $col_render,
    );
  }

  foreach ($items as $id => $item) {
    $variables['rows'][$coordinates[$id]['y']][$coordinates[$id]['x']][] = $item;
  }

}
