<?php

/**
 * @file
 * Views Matrix module file.
 */

/**
 * Preprocess function for views-view-matrix.html.twig.
 */
function views_matrix_preprocess_views_view_matrix(&$variables) {
  $variables['header'] = [];
  $view = $variables['view'];
  $items = $variables['rows'];
  $variables['rows'] = '';
  $style = $view->style_plugin;
  $options = $style->options;
  $fields = $view->field;
  $xfield_id = $options['xconfig']['field'];
  $yfield_id = $options['yconfig']['field'];
  $columns = [];
  $rows = [];
  $columns_renders = [];
  $rows_renders = [];
  $row_header = [];
  $coordinates = [];
  $value_index_lookup = [];
  $first_column_header = $options['xconfig']['first_column'];
  $left_fields = [];
  $right_fields = [];

  // Add rows default and custom CSS classes.
  $variables['default_row_class'] = !empty($options['default_row_class']);

  $variables['header'][] = [
    '#markup' => ' ',
  ];

  // Place headers for fields right of the matrix.
  foreach ($fields as $field_name => $field_handler) {
    if (isset($options['field_positions'][$field_name])
      && $options['field_positions'][$field_name] === 'right'
      && empty($field_handler->options['exclude'])
    ) {
      $right_fields['_' . $field_name] = $field_name;
    }
  }

  // Place headers for fields left of the matrix.
  foreach ($fields as $field_name => $field_handler) {
    if (isset($options['field_positions'][$field_name])
      && $options['field_positions'][$field_name] === 'left'
      && empty($field_handler->options['exclude'])
    ) {
      $variables['header'][] = ['#markup' => ' '];
      $left_fields['_' . $field_name] = $field_name;
    }
  }

  $not_in_matrix = array_flip($left_fields + $right_fields);
  foreach ($items as $id => $item) {
    $xvalue = $variables['view']->style_plugin->getField($id, $xfield_id);
    $yvalue = $variables['view']->style_plugin->getField($id, $yfield_id);

    if (!in_array($xvalue, $columns)) {
      $columns[$id] = $xvalue;
      $value_index_lookup['x'][serialize($xvalue)] = $id;
      $columns_renders[$id] = $xvalue;
    }

    // Whether we've placed this item in the header or not, we can get its
    // coordinate.
    $coordinates[$id]['x'] = $value_index_lookup['x'][serialize($xvalue)];

    if (!in_array($yvalue, $rows)) {
      $row_header[$id] = ['#markup' => $yvalue];
      $rows[$id] = $yvalue;
      $value_index_lookup['y'][serialize($yvalue)] = $id;
      $rows_renders[$id] = $yvalue;
    }
    $coordinates[$id]['y'] = $value_index_lookup['y'][serialize($yvalue)];

    if ($first_column_header) {
      $variables['header'][] = ['#markup' => $first_column_header];
    }
  }

  $column_indices = array_keys($columns_renders);
  foreach (array_keys($rows_renders) as $yindex) {
    $variables['rows'][$yindex]['header'] = $row_header[$yindex];
    if (!empty($left_fields)) {
      $variables['rows'][$yindex]['left_index'] = ['#markup' => ' '];
    }

    foreach ($column_indices as $xindex) {
      $variables['rows'][$yindex][$xindex] = ['#markup' => ' '];
    }

    if (!empty($right_fields)) {
      $variables['rows'][$yindex]['right_index'] = ['#markup' => ' '];
    }
  }

  foreach ($columns_renders as $xindex => $col_render) {
    $variables['header'][] = ['#markup' => $col_render];
  }

  // Place headers for fields right of the matrix.
  foreach ($fields as $field_name => $field_handler) {
    if (isset($options['field_positions'][$field_name])
      && $options['field_positions'][$field_name] === 'right'
      && empty($field_handler->options['exclude'])
    ) {
      $variables['header'][] = ['#markup' => ' '];
    }
  }

  foreach ($items as $id => $item) {

    // If the "Limit to one result per table cell" option is active and there is
    // already data in this table cell, skip this result row.
    if ($options['one_result_per_cell'] && $variables['rows'][$coordinates[$id]['y']][$coordinates[$id]['x']]['#markup'] != " ") {
      continue;
    }

    $rendered_item = '';

    foreach ($fields as $field_name => $field_handler) {
      if ($field_handler->options['exclude']) {
        // Don't render the field.
        continue;
      }

      // Obey the "Hide if empty" setting.
      if ($field_handler->options['hide_empty']) {
        continue;
      }

      if (empty($not_in_matrix[$field_name])) {
        $rendered_item .= '<div><span>' . $variables['view']->style_plugin->getField($id, $field_name) . '</span></div>';
      }
      else {
        if (in_array($field_name, $left_fields)) {
          $variables['rows'][$coordinates[$id]['y']]['left_index']['#markup'] .= '<div><span>' . $variables['view']->style_plugin->getField($id, $field_name) . '</span></div>';
        }
        elseif (in_array($field_name, $right_fields)) {
          $variables['rows'][$coordinates[$id]['y']]['right_index']['#markup'] .= '<div><span>' . $variables['view']->style_plugin->getField($id, $field_name) . '</span></div>';
        }
      }
    }
    $variables['rows'][$coordinates[$id]['y']][$coordinates[$id]['x']]['#markup'] .= $rendered_item;
  }

  // Apply the "Add row numbers" option, if enabled. This has to happen last,
  // because otherwise removing empty rows might mess up the numbering.
  if ($options['yconfig']['row_numbers']) {
    $row_number = 0;
    foreach (array_keys($rows_renders) as $yindex) {
      $header = $variables['rows'][$yindex]['header']['#markup'];
      if ($header) {
        ++$row_number;
        $variables['rows'][$yindex]['header']['#markup'] = $row_number . ') ' . $header;
      }
      unset($header);
    }
  }

}
